---
# This is one Ansible play
- hosts: localhost
  tasks:
    - name: Generate configuration file
      # Template is the name of the Ansible module we're going to execute
      template: src=/home/wblack/pynet_paid/class5/notes/multiple_devices_multiple_cfgs/multi_rtrs_multi_cfgs.j2 
                  dest=/home/wblack/pynet_paid/class5/notes/multiple_devices_multiple_cfgs/{{item.hostname}}.txt
      with_items:
        - {hostname: pynet-rtr1, ip_addr: 1.1.1.1}
        - {hostname: pynet-rtr2, ip_addr: 1.1.1.2}
        - {hostname: pynet-rtr3, ip_addr: 1.1.1.3}
        - {hostname: pynet-rtr4, ip_addr: 1.1.1.4}
        - {hostname: pynet-rtr5, ip_addr: 1.1.1.5}
        - {hostname: pynet-rtr6, ip_addr: 1.1.1.6}
