---

- name: Configure Arista interfaces as access ports
  hosts: arista

  tasks:
    - name: Set Ethernet3 description
      eos_interface: name=Ethernet3 description="*** WB TEST ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Set Ethernet3 to access mode, VLAN200
      eos_switchport: name={{ item }} mode=access access_vlan=200
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet3
