---

- name: Configure Arista interfaces as trunk ports
  hosts: arista

  tasks:
    - name: Set Ethernet3 to trunk mode
      eos_switchport: name={{ item }} mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=100,200
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet3
